<a href="https://colab.research.google.com/github/mamaboss04/week3_lab/blob/main/exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch Fundamentals Exercises

This notebook contains exercises based on the PyTorch Fundamentals tutorial. Each section corresponds to a topic from the original notebook. Complete the exercises by filling in the code cells where indicated.

## 1. Introduction to Tensors

### Exercise 1.1: Create a scalar tensor
Create a scalar tensor with the value 42 and print its value, number of dimensions (ndim), and shape.

In [4]:
import torch

# TODO: Create a scalar tensor
scalar =torch.tensor(42)

# Print details
print(scalar)
print(f"Number of dimensions: {scalar.ndim}")
print(f"Shape: {scalar.shape}")

tensor(42)
Number of dimensions: 0
Shape: torch.Size([])


### Exercise 1.2: Create a vector tensor
Create a vector tensor with values [1, 2, 3, 4] and print its value, ndim, and shape.

In [5]:
# TODO: Create a vector tensor
vector =torch.tensor([1,2,3,4])

# Print details
print(vector)
print(f"Number of dimensions: {vector.ndim}")
print(f"Shape: {vector.shape}")

tensor([1, 2, 3, 4])
Number of dimensions: 1
Shape: torch.Size([4])


### Exercise 1.3: Create a matrix tensor
Create a 2x3 matrix tensor with values [[1, 2, 3], [4, 5, 6]] and print its details.

In [6]:
# TODO: Create a matrix tensor
matrix = torch.tensor([[1,2,3], [4,5,6]])

# Print details
print(matrix)
print(f"Number of dimensions: {matrix.ndim}")
print(f"Shape: {matrix.shape}")

tensor([[1, 2, 3],
        [4, 5, 6]])
Number of dimensions: 2
Shape: torch.Size([2, 3])


### Exercise 1.4: Create a 3D tensor
Create a tensor of shape (2, 2, 2) with sequential values from 1 to 8 using torch.arange and reshape.

In [7]:
# TODO: Create a 3D tensor
tensor_3d = torch.arange(1,9).reshape(2,2,2)

# Print details
print(tensor_3d)
print(f"Number of dimensions: {tensor_3d.ndim}")
print(f"Shape: {tensor_3d.shape}")

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
Number of dimensions: 3
Shape: torch.Size([2, 2, 2])


## 2. Random Tensors

### Exercise 2.1: Create a random tensor
Create a random tensor of shape (4, 4) and print it along with its dtype.

In [8]:
# TODO: Create random tensor
random_tensor = torch.rand(4,4)

print(random_tensor)
print(f"Datatype: {random_tensor.dtype}")

tensor([[0.9422, 0.3029, 0.4298, 0.7564],
        [0.8529, 0.0846, 0.5617, 0.7068],
        [0.7362, 0.3768, 0.0294, 0.4812],
        [0.4373, 0.5787, 0.5197, 0.1080]])
Datatype: torch.float32


### Exercise 2.2: Create an image-sized random tensor
Create a random tensor of shape (3, 224, 224) simulating an image (channels, height, width).

In [9]:
# TODO: Create image-sized random tensor
image_tensor = torch.rand(3,224,224)

print(f"Shape: {image_tensor.shape}")

Shape: torch.Size([3, 224, 224])


## 3. Zeros and Ones

### Exercise 3.1: Create a tensor of zeros
Create a tensor of zeros with shape (5, 5).

In [10]:
# TODO: Create zeros tensor
zeros = torch.zeros(5,5)
print(zeros)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


### Exercise 3.2: Create a tensor of ones like another tensor
Create a random tensor of shape (3, 3), then create a tensor of ones with the same shape using ones_like.

In [11]:
random_tensor = torch.rand(3, 3)
# TODO: Create ones like
ones_like = torch_ones=torch.ones_like(random_tensor)
print(ones_like)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


## 4. Creating Ranges

### Exercise 4.1: Create a range tensor
Create a tensor with values from 0 to 20 with a step of 2 using torch.arange.

In [13]:
# TODO: Create range tensor
range_tensor = torch.arange(0,21)
print(range_tensor)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20])


## 5. Tensor Datatypes

### Exercise 5.1: Create tensors with specific dtypes
Create a tensor with values [1.0, 2.0, 3.0] using dtype=torch.float16 and another with dtype=torch.int64.

In [17]:
# TODO: float16 tensor
float16_tensor = torch.tensor([1.0,2.0,3.0], dtype=torch.float16)
print(float16_tensor)
print(float16_tensor.dtype)

# TODO: int64 tensor
int64_tensor = torch.tensor([1.0,2.0,3.0], dtype=torch.int64)
print(int64_tensor)
print(int64_tensor.dtype)

tensor([1., 2., 3.], dtype=torch.float16)
torch.float16
tensor([1, 2, 3])
torch.int64


### Exercise 5.2: Change dtype
Convert the float16_tensor to float32.

In [20]:
# TODO: Change dtype
float32_tensor = float16_tensor.to(torch.float32)
print(float32_tensor)
print(float32_tensor.dtype)

tensor([1., 2., 3.])
torch.float32


## 6. Getting Information from Tensors

### Exercise 6.1: Print tensor info
Create a random tensor of shape (2, 3, 4) and print its shape, dtype, and device.

In [22]:
# TODO: Create tensor and print info
info_tensor = torch.rand(2,3,4)
print(info_tensor)
print(info_tensor.dtype)
print(info_tensor.device)

tensor([[[0.2918, 0.2523, 0.2027, 0.4183],
         [0.2999, 0.7616, 0.6612, 0.9578],
         [0.7484, 0.6446, 0.5904, 0.9714]],

        [[0.6607, 0.4728, 0.1116, 0.8720],
         [0.5698, 0.9058, 0.9298, 0.3608],
         [0.7560, 0.4642, 0.7228, 0.9169]]])
torch.float32
cpu


## 7. Manipulating Tensors (Basic Operations)

### Exercise 7.1: Perform basic operations
Create a tensor [10, 20, 30]. Add 5, subtract 10, multiply by 2, and divide by 10.

In [33]:
tensor = torch.tensor([10, 20, 30])
# TODO: Add 5
tensor=tensor+5
# TODO: Subtract 10
tensor=tensor-10
# TODO: Multiply by 2
tensor=tensor*2
# TODO: Divide by 10
tensor=tensor/10
print(tensor)

tensor([1., 3., 5.])


### Exercise 7.2: Matrix multiplication
Create two tensors A (2x3) and B (3x2) with random values and perform matrix multiplication.

In [27]:
import torch

# TODO: Create A and B
A = torch.rand(2,3)
B = torch.rand(3,2)

# TODO: Matrix mul using torch.mm
result_mm = torch.mm(A,B)
print(result_mm)

# TODO: Matrix mul using @
result_at = torch.matmul(A,B)
print(result_at)

tensor([[1.3382, 1.3505],
        [0.9808, 1.3800]])
tensor([[1.3382, 1.3505],
        [0.9808, 1.3800]])


## 8. Tensor Aggregation

### Exercise 8.1: Find min, max, mean, sum
Create a tensor with values from 0 to 100 and find its min, max, mean, and sum.

In [40]:
agg_tensor = torch.arange(0, 101)
# TODO: Min
agg_tensor_min=agg_tensor.min()
# TODO: Max
agg_tensor_max=agg_tensor.max()
# TODO: Mean (note: may need to cast to float)
agg_tensor_mean=agg_tensor.type(torch.float32).mean()
# TODO: Sum
agg_tensor_sum=agg_tensor.sum()
print(agg_tensor)
print(agg_tensor_min)
print(agg_tensor_max)
print(agg_tensor_mean)

tensor([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
         28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,
         42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,
         56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,
         70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,
         84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,
         98,  99, 100])
tensor(0)
tensor(100)
tensor(50.)


### Exercise 8.2: Argmin and argmax
Find the positions of the minimum and maximum values in the above tensor.

In [41]:
# TODO: Argmin
import torch
agg_tensor = torch.arange(0, 101)
agg_tensor_argmin = agg_tensor.argmin()
print(agg_tensor_argmin)
# TODO: Argmax
agg_tensor_argmax = agg_tensor.argmax()
print(agg_tensor_argmax)

tensor(0)
tensor(100)


## 9. Reshaping, Stacking, Squeezing, Unsqueezing

### Exercise 9.1: Reshape a tensor
Create a tensor of shape (10,) and reshape it to (2, 5).

In [44]:
reshape_tensor = torch.arange(10)
# TODO: Reshape
reshaped = torch.reshape(reshape_tensor, (2,5))
print(reshaped)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


### Exercise 9.2: Stack tensors
Create two tensors of shape (2, 2) and stack them vertically and horizontally.

In [48]:
tensor1 = torch.rand(2, 2)
tensor2 = torch.rand(2, 2)
# TODO: Stack vertically (dim=0)
ver=torch.stack([tensor1, tensor2], dim=0)
print(ver)
# TODO: Stack horizontally (dim=1)
ver1=torch.vstack([tensor1, tensor2])
print(ver1)

tensor([[[0.5002, 0.6152],
         [0.6283, 0.6972]],

        [[0.5420, 0.5651],
         [0.0891, 0.8486]]])
tensor([[0.5002, 0.6152],
        [0.6283, 0.6972],
        [0.5420, 0.5651],
        [0.0891, 0.8486]])


### Exercise 9.3: Squeeze and unsqueeze
Create a tensor of shape (1, 3, 1), squeeze it, then unsqueeze it back on dim=0.

In [49]:
squeeze_tensor = torch.rand(1, 3, 1)
# TODO: Squeeze
squeezed = torch.squeeze(squeeze_tensor)
print(squeezed)

# TODO: Unsqueeze on dim=0
unsqueezed = torch.unsqueeze(squeezed, dim=0)
print(unsqueezed)

tensor([0.1901, 0.3035, 0.6512])
tensor([[0.1901, 0.3035, 0.6512]])


### Exercise 9.4: Permute
Create an image tensor (3, 100, 100) and permute it to (100, 100, 3).

In [50]:
image_tensor = torch.rand(3, 100, 100)
# TODO: Permute
permuted = torch.permute(image_tensor, (1,2,0))
print(permuted)

tensor([[[0.4057, 0.7652, 0.5558],
         [0.8156, 0.1937, 0.1260],
         [0.6753, 0.4919, 0.2309],
         ...,
         [0.0725, 0.2779, 0.8986],
         [0.6668, 0.4001, 0.1778],
         [0.9555, 0.6823, 0.5179]],

        [[0.7210, 0.8578, 0.3707],
         [0.5061, 0.1271, 0.9190],
         [0.0619, 0.2602, 0.4035],
         ...,
         [0.9174, 0.0781, 0.6131],
         [0.8906, 0.2649, 0.1772],
         [0.1916, 0.5966, 0.7949]],

        [[0.1347, 0.4022, 0.6688],
         [0.0601, 0.6451, 0.8714],
         [0.7513, 0.9306, 0.9018],
         ...,
         [0.0989, 0.6925, 0.5374],
         [0.8223, 0.5040, 0.7203],
         [0.5078, 0.2094, 0.5939]],

        ...,

        [[0.8810, 0.9146, 0.5457],
         [0.1353, 0.4313, 0.4766],
         [0.1840, 0.0411, 0.9765],
         ...,
         [0.0445, 0.5079, 0.2067],
         [0.6630, 0.2513, 0.1301],
         [0.8362, 0.8073, 0.6602]],

        [[0.4917, 0.6313, 0.9634],
         [0.4396, 0.3547, 0.3401],
         [0.

## 10. Indexing

### Exercise 10.1: Index into a tensor
Create a tensor [[[1,2,3],[4,5,6],[7,8,9]]] and index to get 5, then the entire second row.

In [46]:
index_tensor = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
# TODO: Get 5
a=index_tensor[0][1][1]
print(a)
# TODO: Get second row [4,5,6]
b=index_tensor[0][1]
print(b)

tensor(5)
tensor([4, 5, 6])


## 11. PyTorch and NumPy

### Exercise 11.1: NumPy to PyTorch
Create a NumPy array [1,2,3,4] and convert it to a PyTorch tensor.

In [45]:
import numpy as np
numpy_array = np.array([1,2,3,4])
# TODO: Convert to tensor
from_numpy = torch.from_numpy(numpy_array)
print(from_numpy)

tensor([1, 2, 3, 4])


### Exercise 11.2: PyTorch to NumPy
Create a PyTorch tensor [5,6,7,8] and convert it to a NumPy array.

In [43]:
pytorch_tensor = torch.tensor([5,6,7,8])
# TODO: Convert to NumPy
to_numpy = pytorch_tensor.numpy()
print(to_numpy)

[5 6 7 8]


## 12. Reproducibility

### Exercise 12.1: Set manual seed
Set the manual seed to 77 and create two random tensors of shape (2,2). Check if they are equal.

In [42]:
# TODO: Set seed
torch.manual_seed(77)
rand1 = torch.rand(2,2)
print(rand1)

# TODO: Reset seed for second tensor

rand2 = torch.rand(2,2)
print(rand2)

# Check equality
print(rand1 == rand2)

tensor([[0.2919, 0.2857],
        [0.4021, 0.4645]])
tensor([[0.9503, 0.2564],
        [0.6645, 0.8609]])
tensor([[False, False],
        [False, False]])


## 13. Running on GPUs

### Exercise 13.1: Check for GPU
Write code to check if CUDA is available and set the device accordingly.

In [31]:
# TODO: Set device
device = 'cuda' if torch.cuda.is_available() else 'cpu'

### Exercise 13.2: Move tensor to GPU
Create a tensor and move it to the GPU if available. Then move it back to CPU and convert to NumPy.

In [32]:
gpu_tensor = torch.tensor([10, 20, 30])
# TODO: Move to device
gpu_tensor = gpu_tensor.to(device)
print(gpu_tensor)

# TODO: Move back to CPU and to NumPy
cpu_numpy = gpu_tensor.cpu().numpy()

tensor([10, 20, 30])
